name: NeoMHCI
path: ./checkpoints

model:
  mode: emb
  emb_size: 16
  conv_size: [9, 11, 13]
  conv_num: [128, 64, 32]
  conv_off: [2, 1, 0]
  dropout: 0.25
  linear_size: [256, 128]
  peptide_pad: 3
  selection_layer: SGLU
  attn_para:
    pep_len: 21
    in_channel: 16
    hidden_layer_size: 16
    dropout_rate: 0.1
  MIL_module: MIL_DotGateAttn
  MIL_module_config:
    in_channel: 128
    hidden_size: 128

test:
  batch_size: 128

EL_padding:
  mode: emb
  peptide_len: 15
  peptide_pad: 3
  mhc_len: 34
